name: '8'
favicon: null
layout_spectrum: 0.09602731745690107
typography_spectrum: 0.7350434309337288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2505777257028967
  lightness: 0.771431116387248
  saturation: 0.2885513112414628
  rhythmicContrast: 0.7741541597060859
purpose: []
